org.gradle.jvmargs=-Xmx3G

org.gradle.parallel=false
org.gradle.caching=false

org.gradle.java.installations.auto-download=false
org.gradle.java.installations.paths=C:\\Program Files\\Java\\jdk-17

anvilssearch.version=1.0.1-1.19.2
anvilssearch.minecraft=1.19.2
anvilssearch.forge=43.3.0
anvilssearch.mantle=1.10.48
anvilssearch.tconstruct=3.8.5.58

anvilssearch.tinkerssearch.slug=tinkers-search
anvilssearch.tinkerssearch.projectId=1664879
anvilssearch.tinkerssearch.fileId=9070212